In [1]:
#导入NumPy包
# importing numpy package
import numpy as np

# 5.2 为何Numyp 数组优于列表

In [ ]:
# 5.2 为何Numyp 数组优于列表
distance = [55,60,45]
speed = [6,10,7]
time = distance/speed
print("time: ",time)

In [3]:
#列表不能够直接进行数学计算！！ 
#NumPy数组 ===>
import numpy as np
distance = [55,40,29]
speed = [3,4,6]
dist = np.array(distance)
spd = np.array(speed)
time = dist/spd
print(time)


[18.33333333 10.          4.83333333]


In [4]:
# dist和spd变量是NumPy数组类型，所以结果将自动设定为NumPy数组。

# 5.3 NumPy数组属性

In [7]:
# 5.3 NumPy数组属性
# NumPy数组有自己的属性，如维度，尺寸和形状，可以通过ndim、shape和size属性
# 来获取对应的值。
# data type
print("data type of array:",time.dtype)
# No. of dimensions
print("No. of dimensions:", time.ndim)
# size of each dimension
print("size of each dimension:", time.shape)
# total size of array
print("total size of array:", time.size)

data type of array: float64
No. of dimensions: 1
size of each dimension: (3,)
total size of array: 3


# 5.4 创建NumPy数组

In [12]:
# 5.4 创建NumPy数组
# creating arrays with random values
np.random.seed(0)  # seed for reproducibility 将随机种子设为0

x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3,4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3,4,5)) # Three-dimensional array

print("x1 ndim: ", x1.ndim)
print("x1 shape: ", x1.shape)
print("x1 size: ", x1.size)

print("x2 ndim: ", x2.ndim)
print("x2 shape: ", x2.shape)
print("x2 size: ", x2.size)

print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x1 ndim:  1
x1 shape:  (6,)
x1 size:  6
x2 ndim:  2
x2 shape:  (3, 4)
x2 size:  12
x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


# numpy.random.randint
random.randint(low,high=None,size=None,dtpye=int)

Return random integers from low(inclusive)to high(exclusive)

[low,high)  if high is None then [0,low)


In [13]:
np.random.randint(2,size=10)

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 1])

In [15]:
np.random.randint(6,size=5)

array([4, 3, 2, 5, 5])

In [17]:
np.random.randint(5,size=(3,4))

array([[2, 2, 0, 1],
       [0, 2, 2, 3],
       [2, 3, 2, 1]])

In [18]:
np.random.randint(5,size=(4,3))

array([[2, 3, 3],
       [3, 2, 3],
       [4, 1, 2],
       [3, 1, 2]])

使用NumPy的arange()函数创建另一个数组，该函数返回的值基本上在给定的区间内均匀分布。

In [20]:
# 等差数组
f = np.arange(0,20,5)
print("sequential array with steps of 5:\n",f)

sequential array with steps of 5:
 [ 0  5 10 15]


# 5.5 访问NumPy数组中的元素

In [22]:
# 1-d array
print("1-d array:", x1)
print("second element of first array:", x1[1])
print("last element of first array:", x1[-1])
print("first element of first array:", x1[0])

1-d array: [5 0 3 3 7 9]
second element of first array: 0
last element of first array: 9
first element of first array: 5


In [23]:
# 2-d array
print("2-d array:\n",x2)
print("first element of 2-d array:", x2[0,0])
print("3-d array:\n",x3)
print("first element of 3-d array:", x3[0,0,0])

2-d array:
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
first element of 2-d array: 3
3-d array:
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
first element of 3-d array: 8


# 5.6 NumPy数组的切片