In [7]:
#导入NumPy包
# importing numpy package
import numpy as np

# 5.2 为何Numyp 数组优于列表

In [6]:
# 5.2 为何Numyp 数组优于列表
distance = [55,60,45]
speed = [6,10,7]
time = distance/speed
print("time: ",time)

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [8]:
#列表不能够直接进行数学计算！！ 
#NumPy数组 ===>
import numpy as np
distance = [55,40,29]
speed = [3,4,6]
dist = np.array(distance)
spd = np.array(speed)
time = dist/spd
print(time)


[18.33333333 10.          4.83333333]


In [4]:
# dist和spd变量是NumPy数组类型，所以结果将自动设定为NumPy数组。

# 5.3 NumPy数组属性

In [7]:
# 5.3 NumPy数组属性
# NumPy数组有自己的属性，如维度，尺寸和形状，可以通过ndim、shape和size属性
# 来获取对应的值。
# data type
print("data type of array:",time.dtype)
# No. of dimensions
print("No. of dimensions:", time.ndim)
# size of each dimension
print("size of each dimension:", time.shape)
# total size of array
print("total size of array:", time.size)

data type of array: float64
No. of dimensions: 1
size of each dimension: (3,)
total size of array: 3


# 5.4 创建NumPy数组

In [9]:
# 5.4 创建NumPy数组
# creating arrays with random values
np.random.seed(0)  # seed for reproducibility 将随机种子设为0

x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3,4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3,4,5)) # Three-dimensional array

print("x1 ndim: ", x1.ndim)
print("x1 shape: ", x1.shape)
print("x1 size: ", x1.size)

print("x2 ndim: ", x2.ndim)
print("x2 shape: ", x2.shape)
print("x2 size: ", x2.size)

print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x1 ndim:  1
x1 shape:  (6,)
x1 size:  6
x2 ndim:  2
x2 shape:  (3, 4)
x2 size:  12
x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


# numpy.random.randint
random.randint(low,high=None,size=None,dtpye=int)

Return random integers from low(inclusive)to high(exclusive)

[low,high)  if high is None then [0,low)


In [10]:
np.random.randint(2,size=10)

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 1])

In [11]:
np.random.randint(6,size=5)

array([4, 3, 2, 5, 5])

In [12]:
np.random.randint(5,size=(3,4))

array([[0, 1, 1, 3],
       [0, 0, 1, 2],
       [4, 2, 0, 3]])

In [13]:
np.random.randint(5,size=(4,3))

array([[2, 2, 0],
       [1, 0, 2],
       [2, 3, 2],
       [3, 2, 1]])

使用NumPy的arange()函数创建另一个数组，该函数返回的值基本上在给定的区间内均匀分布。

In [14]:
# 等差数组
f = np.arange(0,20,5)
print("sequential array with steps of 5:\n",f)

sequential array with steps of 5:
 [ 0  5 10 15]


# 5.5 访问NumPy数组中的元素

In [15]:
# 1-d array
print("1-d array:", x1)
print("second element of first array:", x1[1])
print("last element of first array:", x1[-1])
print("first element of first array:", x1[0])

1-d array: [5 0 3 3 7 9]
second element of first array: 0
last element of first array: 9
first element of first array: 5


In [16]:
# 2-d array
print("2-d array:\n",x2)
print("first element of 2-d array:", x2[0,0])
print("3-d array:\n",x3)
print("first element of 3-d array:", x3[0,0,0])

2-d array:
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
first element of 2-d array: 3
3-d array:
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
first element of 3-d array: 8


# 5.6 NumPy数组的切片

我们不光可以使用括号访问单个数组元素，也可以使用它来访问带有切片符号（用冒号字符标记）的子数组。

与列表不同，数组切片返回的是数组数据的试图，不是副本。如果为数组创建一个子数组，然后修改企中的任何元素，那么院是数组也将被修改。

In [29]:
# create an array
x = np.arange(10)
print("our array:", x)
print("first five elements:",x[:5])
print("elements after index 5:",x[5:])
print("middle sub-array:",x[4:7])
print("every other element:", x[::2])
print("every other element, starting at index 1:", x[1::2])
print("elements in reversed order:", x[::-1])

our array: [0 1 2 3 4 5 6 7 8 9]
first five elements: [0 1 2 3 4]
elements after index 5: [5 6 7 8 9]
middle sub-array: [4 5 6]
every other element: [0 2 4 6 8]
every other element, starting at index 1: [1 3 5 7 9]
elements in reversed order: [9 8 7 6 5 4 3 2 1 0]


多维数组用逗号。

In [30]:
print("2-d array:\n",x2)
print("two rows, three columns:\n", x2[:2,:3])

2-d array:
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
two rows, three columns:
 [[3 5 2]
 [7 6 8]]


如果创建一个数组的子数组并对该子数组进行更改，那么原属数组也会随之更改。为确保数组的数据完整性，使用copy（）辅助原始数组，然后可以在不影响原始数组的情况下对组数组进行修改。

In [31]:
# original array
print("original 2-d array:\n",x2)
# creating a 2x2 subarray from the original array
x2_sub = x2[:2,:2]
print("sub-array:\n", x2_sub)
# modifying sub-array
x2_sub[0,0] = 88
print("modified sub array:\n", x2_sub)
# orignial array after sub-array changes
print("original array after changes in sub-array:\n",x2)
print("making a copy of the original array")
x2_sub_copy = x2[:2,:2].copy()
print("copy of the original array:\n", x2_sub_copy)
# modifying copied array
x2_sub_copy[0,0] = 42
print("copied array after changes:\n", x2_sub_copy)
print("original array:\n",x2)

original 2-d array:
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
sub-array:
 [[3 5]
 [7 6]]
modified sub array:
 [[88  5]
 [ 7  6]]
original array after changes in sub-array:
 [[88  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
making a copy of the original array
copy of the original array:
 [[88  5]
 [ 7  6]]
copied array after changes:
 [[42  5]
 [ 7  6]]
original array:
 [[88  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


# 5.7 数组连接

In [32]:
# 数组合并：  
# np.concatenate()    用于相同维度数组的合并
# np.vstack()         处理混合维度的数组
# np.hstack()         处理混合维度的数组


In [33]:
# creating two sample arrays
x = np.array([1,2,3])
y = np.array([3,2,1])
# combining both arrays using concatenate
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [34]:
# creating a sample array
x = np.array([1,2,3])
# creating a 2-d array
grid = np.array([[9,8,7],
               [6,5,4]])
# vertically stack the arrays
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [35]:
# horizontally stack the arrays
y = np.array([[99],[99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])